### PR TITLE
Modify default files for all QU resolutions.

### PR DESCRIPTION
**Pull request by gdicker1**
Makes the setup/build process of oQU{120,60,30,15,7.5,3.75} mesh compsets easier by selecting the correct decomp files by default.

Also adds free format options for ifx and nvhpc compilers.

### CODE REVIEW

**Comment by dazlich** [comment]
I’ve got a one line fix to buildlib that takes care of the intel compilation issue with the one seaice file.
Can you replace line 114 (for compiler = intel) with:
            fixedflags =  '"-UCPRINTEL -free"'


Thanks

Don

On Sep 15, 2023, at 11:24 AM, gdicker1 ***@***.***> wrote:


** Caution: EXTERNAL Sender **


@gdicker1<https://github.com/gdicker1> requested your review on: #2<https://github.com/EarthWorksOrg/mpas-seaice/pull/2> Modify default files for all QU resolutions..

**Comment by dazlich** [comment]
Just to elaborate, this is a hack that insures the -UCPRINTEL gets placed after the -DCPRINTEL for intel.


On Sep 16, 2023, at 9:24 AM, Don Dazlich ***@***.***> wrote:

I’ve got a one line fix to buildlib that takes care of the intel compilation issue with the one seaice file.
Can you replace line 114 (for compiler = intel) with:
            fixedflags =  '"-UCPRINTEL -free"'


Thanks

Don

On Sep 15, 2023, at 11:24 AM, gdicker1 ***@***.***> wrote:


** Caution: EXTERNAL Sender **


@gdicker1<https://github.com/gdicker1> requested your review on: #2<https://github.com/EarthWorksOrg/mpas-seaice/pull/2> Modify default files for all QU resolutions..

**Comment by gdicker1** [comment]
@dazlich, I'm testing that fix now. I think it would be fine to add to this PR, but I can't actually push to your branch. I get a "permission denied" error

**Comment by dazlich** [comment]
I’ve got it committed now in my branch on GitHub. Is that sufficient for you to work with it?


On Sep 18, 2023, at 11:23 AM, gdicker1 ***@***.***> wrote:


** Caution: EXTERNAL Sender **


@dazlich<https://github.com/dazlich>, I'm testing that fix now. I think it would be fine to add to this PR, but I can't actually push to your branch. I get a "permission denied" error

**Comment by gdicker1** [comment]
Closed by merge

**Pull request closed without merging**
