### PR TITLE
Update mpas-ocean version

### PR DESCRIPTION
**Pull request by dazlich**
The mpas-ocean component is updated to a new version: branch 'vanroekel/ocean/update-nonhydro-2-15-2023' of https://github.com/vanroekel/E3SM . This new version permits GPU acceleration to be implemented to the ocean, and features a non-hydrostatic treatment of the vertical coordinate in the split-implicit time integration scheme.

The changes in mpas-seaice involve importing the entire new version. This was the simplest way to deal with the associated changed in mpas-framework.

This is part of a package of PRs for branches named update/ocean:
EarthWorksOrg /mpas-ocean PR [#15](https://github.com/EarthWorksOrg/mpas-ocean/pull/15)
EarthWorksOrg /mpas-seaice PR [#17](https://github.com/EarthWorksOrg/mpas-seaice/pull/17)
EarthWorksOrg /mpas-framework PR [#10](https://github.com/EarthWorksOrg/mpas-framework/pull/10)
EarthWorksOrg /CMEPS PR [#12](https://github.com/EarthWorksOrg/CMEPS/pull/12)
EarthWorksOrg/EarthWorks PR [#75](https://github.com/EarthWorksOrg/EarthWorks/pull/75) (incorporates above)

To clone this version of Earthworks use the update/ocean branch.

### CODE REVIEW

**Comment by dazlich** [comment]
These associated PRs need to be updated
EarthWorksOrg /mpas-ocean PR [#15](https://github.com/EarthWorksOrg/mpas-ocean/pull/15)
EarthWorksOrg /mpas-seaice PR [#17](https://github.com/EarthWorksOrg/mpas-seaice/pull/17)
EarthWorksOrg /mpas-framework PR [#10](https://github.com/EarthWorksOrg/mpas-framework/pull/10)
EarthWorksOrg /CMEPS PR [#12](https://github.com/EarthWorksOrg/CMEPS/pull/12)
EarthWorksOrg/EarthWorks PR [#75](https://github.com/EarthWorksOrg/EarthWorks/pull/75) (incorporates above)

**Comment by dazlich** [comment]
Also, I have merge issues to deal with with EarthWorksOrg /mpas-ocean PR [#15](https://github.com/EarthWorksOrg/mpas-ocean/pull/15)

**Comment by dazlich** [comment]
One note on this seaice port - it required a shared constant that is in the E3SM shr_const_mod.F90 but not in the CESM/EarthWorks version. I have added the declaration for it:
```
real(kind=dbl_kind),parameter :: SHR_CONST_MWC     = 12.0107_dbl_kind      ! molecular weight carbon
```
in mpas-seaice/src/column/constants/cesm/ice_constants_colpkg.F90.

Do we want this declaration to get into the share/src/shr_const_mod.F90 file?

**Comment by gdicker1** [comment]
> Do we want this declaration to get into the share/src/shr_const_mod.F90 file?

That would be reasonable, but I have two thoughts that conflict and make me think that the code in this PR is good enough.

- The easiest thing would be to fork the CESM_share repo under EarthWorksOrg and add this change, but we're trying to be closer in synch with CESM. So I don't think another fork would be good right now.
- I also don't think it would be worthwhile to slow this PR down while we wait for a PR to the ESCOMP/CESM_share repo to be accepted. (Admittedly, this is a super small change that could be quick).

I think we could "earmark" this in an Issue and delay the issue of adding this to CESM_share.

**Comment by dazlich** [comment]
Agreed
Sent from my iPhone

On Oct 15, 2024, at 4:39 PM, G. Dylan Dickerson ***@***.***> wrote:

﻿

** Caution: EXTERNAL Sender **

Do we want this declaration to get into the share/src/shr_const_mod.F90 file?

That would be reasonable, but I have two thoughts that conflict and make me think that the code in this PR is good enough.

  *   The easiest thing would be to fork the CESM_share repo under EarthWorksOrg and add this change, but we're trying to be closer in synch with CESM. So I don't think another fork would be good right now.
  *   I also don't think it would be worthwhile to slow this PR down while we wait for a PR to the ESCOMP/CESM_share repo to be accepted. (Admittedly, this is a super small change that could be quick).

I think we could "earmark" this in an Issue and delay the issue of adding this to CESM_share.

**Review by gdicker1 — APPROVED** [review]

**Review by gdicker1 — APPROVED** [review]

**Pull request merged**
