### PR TITLE
Fix Intel OneAPI builds

### PR DESCRIPTION
**Pull request by gdicker1**
This fix addresses an Internal Compiler Error that would occur with only the OneAPI compilers in mpas_seaice_core_interface.F90.

### CODE REVIEW

**Review by dazlich — APPROVED** [review]
I've tested this with the fully coupled model at 120, 60, 30 and 15km with ifx - they all pass and I've updated the required runs document.

Looks good, thanks

**Comment by dazlich** [comment]
@gdicker1 - There is also a one line change in cime-config/buildlib that got missed for v2.0 that needs to also be committed for intel-oneapi compilation:

diff --git a/cime_config/buildlib b/cime_config/buildlib
index f7f333c..ee61712 100755
--- a/cime_config/buildlib
+++ b/cime_config/buildlib
@@ -113,7 +113,7 @@ def _build_mpassi():
         if compiler == 'intel':
             fixedflags =  '"-UCPRINTEL -free"'
         elif compiler == 'intel-oneapi':
-            fixedflags =  '-free'
+            fixedflags =  '"-UCPRINTEL -free"'
         elif compiler == 'gnu':
             fixedflags =  '-ffree-form'
         elif compiler == 'nvhpc':

**Comment by gdicker1** [comment]
@dazlich thanks for the catch! Does [c4c33ad](https://github.com/EarthWorksOrg/mpas-seaice/pull/4/commits/c4c33ada6743212d7c4e4479eda39a65def06e83) fix it for you?

**Comment by dazlich** [comment]
Looks good, thanks!

On Jan 30, 2024, at 10:43 AM, G. Dylan Dickerson ***@***.***> wrote:


** Caution: EXTERNAL Sender **


@dazlich<https://github.com/dazlich> thanks for the catch! Does c4c33ad<https://github.com/EarthWorksOrg/mpas-seaice/pull/4/commits/c4c33ada6743212d7c4e4479eda39a65def06e83> fix it for you?

**Pull request merged**
