### PR TITLE
Add config_dt for 60km to 3.75km oQU grids

### PR DESCRIPTION
**Pull request by gdicker1**
This is an attempt to use the namelist files to select the `config_dt` for mpas-si instead of doing it in an user_nl_mpassi file or by shell commands.

Important context for these values: https://github.com/EarthWorksOrg/EarthWorks/pull/45#issuecomment-2118165239

### CODE REVIEW

**Comment by gdicker1** [comment]
@dazlich, I'm not certain of these values but thought they would be a good "first stab" at the settings. Let me know what you think!

**Review by dazlich — COMMENTED** [review]
Are these the values that have been used with QPC6? I think QPC6 jets may not be quite so strong as we will get in an F-case or fully-coupled. We may need have different sets for different cases. I know my 30km F simulations require shorter than 450s - I've been using 240s, not sure we can get away with 300s.

**Comment by dazlich** [comment]
Let's find out what Brian Dobbins is using for the 3.75km DYAMOND case and work up from there.

**Review by dazlich — COMMENTED** [review]
oops, these are for the ice (and ocean presumably, too). I should've looked more closely.

These should be 2*mpas_dt, which should also be the coupling interval/cam physics timestep.  Do we have defaults set for mpas_dt?

**Review by dazlich — APPROVED** [review]
Just heard from Brian Dobbins about what he is doing - In QPC6 at 3.75km he is using mpas_dt = 20s and a coupling frequency of 60s - this matches  config_dt=60. which you suggested. The coarser resolutions match up with reasonable mpas_dt*3. So it looks good to me.

Will you be doing the same for the mpas-ocean?

**Comment by gdicker1** [comment]
> Just heard from Brian Dobbins about what he is doing - In QPC6 at 3.75km he is using mpas_dt = 20s and a coupling frequency of 60s - this matches config_dt=60. which you suggested. The coarser resolutions match up with reasonable mpas_dt*3. So it looks good to me. 

Thanks for checking on this, I'm glad the first stab was right!

> Will you be doing the same for the mpas-ocean?

It looks like we already have some in [namelist_defaults_mpaso.xml L37-45](https://github.com/EarthWorksOrg/mpas-ocean/blob/b7d350ab51fad1b9a1bc6466176df6f23352f38f/bld/namelist_files/namelist_defaults_mpaso.xml#L37-L45). Do you think those are appropriate?

**Comment by dazlich** [comment]
Except for QU120, the defaults need to be changed for the ocean and set identical to the ones in seaice.

On May 16, 2024, at 8:47 AM, G. Dylan Dickerson ***@***.***> wrote:


** Caution: EXTERNAL Sender **


Just heard from Brian Dobbins about what he is doing - In QPC6 at 3.75km he is using mpas_dt = 20s and a coupling frequency of 60s - this matches config_dt=60. which you suggested. The coarser resolutions match up with reasonable mpas_dt*3. So it looks good to me.

Thanks for checking on this, I'm glad the first stab was right!

Will you be doing the same for the mpas-ocean?

It looks like we already have some in namelist_defaults_mpaso.xml L37-45<https://github.com/EarthWorksOrg/mpas-ocean/blob/b7d350ab51fad1b9a1bc6466176df6f23352f38f/bld/namelist_files/namelist_defaults_mpaso.xml#L37-L45>. Do you think those are appropriate?

**Comment by gdicker1** [comment]
> Except for QU120, the defaults need to be changed for the ocean and set identical to the ones in seaice.

Understood, I'll get this PR merged and open a similar one in EWOrg/MPAS-O. I plan to include these as part of [EWOrg/EW #45](https://github.com/EarthWorksOrg/EarthWorks/pull/45)

**Comment by dazlich** [comment]
Great!

On May 16, 2024, at 9:35 AM, G. Dylan Dickerson ***@***.***> wrote:


** Caution: EXTERNAL Sender **


Except for QU120, the defaults need to be changed for the ocean and set identical to the ones in seaice.

Understood, I'll get this PR merged and open a similar one in EWOrg/MPAS-O. I plan to include these as part of EWOrg/EW #45<https://github.com/EarthWorksOrg/EarthWorks/pull/45>

**Pull request merged**
