### PR TITLE
Elimination of conflicting external references

### PR DESCRIPTION
**Pull request by dazlich**
These modifications allow for the elimination of conflicting external references at the link step of compilation. They go hand in hand with branches of the same name in mpas-framework and mpas-seaice. The buildlib now has some sed statements that replace a dummy string through the framework files and rename them in the bld/ice/source directory. Module use statements in the ocean source are changed from 'use mpas_...' to 'use mpass_...' to match processing of the framework.

### CODE REVIEW

**Comment by dazlich** [comment]
Looks like the previous PR slipped a cime_config file in. How do I eliminate it?

**Comment by dazlich** [comment]
I've got the conflicts worked out, and the prescribe seaice mode changes in the develop branch are now merge in, so review away @gdicker1 @areanddee @sherimickelson @supreethms1809

**Comment by gdicker1** [comment]
See also: https://github.com/EarthWorksOrg/mpas-framework/pull/7 and https://github.com/EarthWorksOrg/mpas-ocean/pull/7

**Comment by gdicker1** [comment]
> Looks like the previous PR slipped a cime_config file in. How do I eliminate it?

I think when I tested merging this PR into ew-develop it resolved itself. I'll make a follow-up PR to add some more things to the .gitignore so files like `*.pyc` or `*.swp` don't get included.

**Comment by dazlich** [comment]
Ok, thanks!

On Mar 29, 2024, at 12:32 PM, G. Dylan Dickerson ***@***.***> wrote:


** Caution: EXTERNAL Sender **


Looks like the previous PR slipped a cime_config file in. How do I eliminate it?

I think when I tested merging this PR into ew-develop it resolved itself. I'll make a follow-up PR to add some more things to the .gitignore so files like *.pyc or *.swp don't get included.

**Review by gdicker1 — APPROVED** [review]
I now think my issue with the term "external reference" in the commit message isn't worth these changes waiting any longer. Without further discussion or thoughts, I plan to merge these PRs and [EWOrg/EW #39](https://github.com/EarthWorksOrg/EarthWorks/pull/39) later this afternoon.

**Pull request merged**
